services:
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./container/prometheus:/etc/prometheus
      - ./data/monitoring/prometheus:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
  proxmox-exporter:
    image: ghcr.io/danielr1996/proxmox-exporter:latest
    restart: unless-stopped
    ports:
      - 9876:9876
    environment:
      PROXMOX_HOST: proxmox.app.danielr1996.de
      PROXMOX_PORT: 80
      PROXMOX_USERNAME: root@pam
    env_file:
      .env
