global:
  scrape_interval: 5s
  scrape_timeout: 4s

scrape_configs:
  - job_name: 'pve'
    static_configs:
      - targets:
          - proxmox-exporter:9876
    metrics_path: /metrics
  - job_name: 'tasmota'
    static_configs:
      - targets:
          - 10.0.0.115
    metrics_path: /metrics
  - job_name: 'ceph'
    static_configs:
      - targets:
        - 10.0.0.118:9283
    metrics_path: /metrics
